---
###########################
# Setup Kubernetes Cluster
###########################

# NOTICE:
# You Must specify profile name as an extra var (--extra-vars "profile=XXXX") 

- hosts: localhost
  connection: local
  gather_facts: True
  vars_files:
    - "../profiles/{{ profile }}.yml"

  roles:
    - k8s_create_cluster
    - certificates
    - aws_resources
    - k8s_resources
