- name: install the required dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - openssl
  - python-openssl
  connection: local

- name: "create the {{ ler53_cert_dir }} directory"
  become: yes
  file:
    path: "{{ ler53_cert_dir }}"
    state: directory
    owner: "{{ whoami_output.stdout }}"
    mode: 0755
  connection: local

- name: "create the {{ ler53_account_key_dir }} directory"
  become: yes
  file:
    path: "{{ ler53_account_key_dir }}"
    owner: "{{ whoami_output.stdout }}"
    mode: 0700
    state: directory
  connection: local

- name: generate the private key
  openssl_privatekey:
    path: "{{ ler53_cert_dir }}/{{ ler53_key_file_name }}"
    size: "{{ ler53_key_size }}"
  connection: local

- name: set the private key file permissions
  become: yes
  file:
    path: "{{ ler53_cert_dir }}/{{ ler53_key_file_name }}"
    owner: "{{ whoami_output.stdout }}"
    group: "{{ whoami_output.stdout }}"
    mode: "{{ ler53_cert_files_mode }}"
  connection: local

- name: generate the CSR
  openssl_csr:
    path: "{{ ler53_cert_dir }}/{{ ler53_csr_file_name }}"
    privatekey_path: "{{ ler53_cert_dir }}/{{ ler53_key_file_name }}"
    common_name: "{{ ler53_cert_common_name }}"
    key_usage: "{{ ler53_cert_key_usages }}"
    subject_alt_name: "DNS:{{ ler53_cert_common_name }},DNS:*.{{ ler53_cert_common_name }}"
  register: generate_csr
  connection: local

- name: set the CSR file permissions
  become: yes
  file:
    path: "{{ ler53_cert_dir }}/{{ ler53_csr_file_name }}"
    owner: "{{ whoami_output.stdout }}"
    group: "{{ whoami_output.stdout }}"
    mode: "{{ ler53_cert_files_mode }}"
  connection: local

- name: generate the Let's Encrypt account key
  openssl_privatekey:
    path: "{{ ler53_account_key_dir }}/{{ ler53_account_key_file_name }}"
    size: "{{ ler53_account_key_size }}"
  connection: local

- name: set the Let's Encrypt account key file permissions
  become: yes
  file:
    path: "{{ ler53_account_key_dir }}/{{ ler53_account_key_file_name }}"
    owner: "{{ whoami_output.stdout }}"
    mode: 0600
  connection: local


- name: delete existing certificate
  become: yes
  file:
    path: "{{ ler53_cert_dir }}/{{ ler53_cert_file_name }}"
    state: absent
  when: generate_csr.changed and ler53_new_cert_when_csr_changes
  connection: local