apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-dag-filler"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-dag-filler"
spec:
  template:
    spec:
      containers:
      - name: alpine
        image: alpine:3.5
        command: ["cp",  "-R", "/mnt/dags/.", "/home/airflow/dags/"]
        volumeMounts:
        - name: dag-volume
          mountPath: /home/airflow/dags
        - name: airflow-dags
          mountPath: /mnt/dags
      restartPolicy: Never
      volumes:
      - name: dag-volume
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-dag-pvc"
      - name: airflow-dags
        configMap:
          name: "{{ .Release.Name }}-dags"