apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-flower"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-flower"
spec:
  selector:
    app: "{{ .Release.Name }}-airflow-flower"
  ports:
    - name: flower
      protocol: TCP
      port: 5555
      targetPort: flower
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-flower"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-flower"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-airflow-flower"
    spec:
      restartPolicy: Always
      containers:
      - name: flower
        image: "{{ .Values.image }}"
        env:
        - name: POSTGRES_HOST
          value: "{{ .Release.Name }}-postgres"
        - name: REDIS_HOST
          value: "{{ .Release.Name }}-redis"
        - name: AIRFLOW_HOME
          value: "/home/airflow"
        - name: FLOWER_PORT
          value: "5555"
        volumeMounts:
        - name: airflow-config
          mountPath: /home/airflow/airflow.cfg
          subPath: airflow.cfg
        - name: dag-volume
          mountPath: /home/airflow/dags
        ports:
        - name: flower
          containerPort: 5555
        args: ["flower"]
      volumes:
      - name: airflow-config
        configMap:
          name: "{{ .Release.Name }}-config"
      - name: dag-volume
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-dag-pvc"
