apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-scheduler"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-scheduler"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-airflow-scheduler"
    spec:
      restartPolicy: Always
      containers:
      - name: scheduler
        image: "{{ .Values.image }}"
        env:
        - name: POSTGRES_HOST
          value: "{{ .Release.Name }}-postgres"
        - name: REDIS_HOST
          value: "{{ .Release.Name }}-redis"
        - name: AIRFLOW_HOME
          value: "/home/airflow"
        volumeMounts:
        - name: airflow-config
          mountPath: /home/airflow/airflow.cfg
          subPath: airflow.cfg
        - name: dag-volume
          mountPath: /home/airflow/dags
        args: ["airflow", "scheduler"]
      volumes:
      - name: airflow-config
        secret:
          secretName: "{{ .Release.Name }}-config"
          items:
          - key: airflow.cfg
            path: airflow.cfg
      - name: dag-volume
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-dag-pvc"