---
- name: Remove legion chart
  shell: helm delete --purge legion-{{ tenant }}
  ignore_errors: true

- name: "Remove {{ tenant }} namespace"
  shell: "kubectl delete namespace {{ tenant }} --ignore-not-found=true --grace-period=10"

- name: "Check that {{ tenant }} namespace has been removed"
  shell: "kubectl get namespace {{ tenant }}"
  register: namespace_check
  until: namespace_check.stderr.find(' not found') != -1
  retries: 5
  delay: 10
  ignore_errors: true

- name: WORKAROUND delete pods in phase terminating
  shell: kubectl --namespace {{ tenant }}  delete --grace-period=0 --force po $(kubectl --namespace {{ tenant }} get po -o wide | grep Terminating | awk '{ print $1 }') || true
