---
- name: Remove legion core chart
  shell: ~/helms/helm_delete_by_chart_name legion-core

- name: Copy git deploy key to host
  copy:
    src: "{{ git_key }}"
    dest: ~/git.deploy
    owner: ubuntu
    group: ubuntu

- name: Remove old GIT secret
  shell: kubectl delete secret legion-git-deploy  --ignore-not-found=true

- name: Create GIT secret
  shell: kubectl create secret generic legion-git-deploy --from-file=id_rsa=/home/ubuntu/git.deploy

- name: Create legion configuration (values) file
  template:
    src: legion-core-values.yaml.j2
    dest: ~/legion-core-values.yaml
    mode: 0644
  vars:
    git_secret_name: legion-git-deploy

- name: Pre run with dumping
  shell: helm install legion-core --name legion-core --debug --dry-run -f  ~/legion-core-values.yaml
  register: helm_install_output
  args:
    chdir: ~/helms

- name: Save pre run result
  copy:
    content: "{{ helm_install_output.stdout }}"
    dest: ~/helm.debug

- name: Save pre run result localy
  local_action:
    module: copy
    content: "{{ helm_install_output.stdout }}"
    dest: ./helm.debug

- name: Install legion core chart
  shell: helm install legion-core --name legion-core --wait --timeout 600 -f  ~/legion-core-values.yaml
  args:
    chdir: ~/helms

- name: Run HELM status checker
  shell: ~/helms/examine_helm_deployed legion-core

- name: Dump current HELM status
  shell: helm status legion-core
  register: helm_status_output

- name: Save HELM status localy
  local_action:
    module: copy
    content: "{{ helm_status_output.stdout }}"
    dest: ./helm.status

