route53_zone: epm.kharlamov.biz
base_domain: k8s-nightly.epm.kharlamov.biz
certificate_email: Kirill_Makhonin@epam.com
git_key: "/home/jenkins/deploy.cert"
cert_dir: "/etc/dynssl"
use_https: "yes"
use_https_for_tests: "no"
subdomains:
  - dashboard
  - nexus
  - jenkins
  - jupyter
  - airflow
  - flower
tenant_subdomains:
  - ldap
  - edge
  - consul
  - grafana
  - edi
tenants:
  - company-a
  - company-b
namespace: default
deployment: legion
use_local_prefix: true
service_account:
  login:  admin
  password: admin
examples_to_test:
  - Test-Summation
  - Sklearn-Income
  - Digit-Recognition
storagepath: hostpath
airflow:
  s3_log_url: 's3://legion-cluster/single_master/airflow-logs/'
  s3_url: 's3://legion-cluster/'
  expected_output: 'expected-data/'
  pvc: 200m