---
- name: get public IP
  ipify_facts:

- name: print public IP
  debug: msg="Public IP - {{ ipify_public_ip }} for domains in {{ root_domain }}."
  
- name: "create the DNS record {{ root_domain }}"
  route53:
    command: create
    zone: "{{ route53_zone }}"
    record: "{{ root_domain }}"
    type: A
    value: "{{ ipify_public_ip }}"
    overwrite: yes
    wait: yes
  connection: local

- name: "create DNS records for {{ domain_delimiter }}{{ root_domain }}"
  route53:
    command: create
    zone: "{{ route53_zone }}"
    record: "{{ subdomain }}{{ domain_delimiter }}{{ root_domain }}"
    type: A
    value: "{{ ipify_public_ip }}"
    overwrite: yes
    wait: yes
  connection: local
  with_items: "{{ current_subdomains }}"
  loop_control:
    loop_var: subdomain

- name: "create DNS records with prefix local- for {{ domain_delimiter }}{{ root_domain }}"
  route53:
    command: create
    zone: "{{ route53_zone }}"
    record: "local-{{ subdomain }}{{ domain_delimiter }}{{ root_domain }}"
    type: A
    value: "{{ ansible_ssh_host }}"
    overwrite: yes
    wait: yes
  connection: local
  with_items: "{{ current_subdomains }}"
  loop_control:
    loop_var: subdomain

